name: Lint GitHub Actions workflows
on:
  push:
    branches: [ checkstyle ]














jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
