name: code check
on:
  push:
    branches: [ datahub ]






















jobs:
  code_check:
    strategy:
      fail-fast: false
      matrix:
        command:
          [
            "check_event_type.py",
            "check_policies.py"
          ]
    name: run code checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 800
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: run check ${{ matrix.command }}
        run: |
          python .github/scripts/${{ matrix.command }}
