name: Lint actions
on:
  push:
    branches: [ datahub ]




jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
