name: Qodana
on:
  push:
    branches: [ datahub ]










jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2022.3.4
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          cache-default-branch-only: true
