name: "Generate release notes"

on:
  push:
    branches: [ checkstyle ]









jobs:
  generate:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-22.04
    steps:
      - name: Download checkstyle
        uses: actions/checkout@v3

      - name: Setup local maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Generate release notes
        env:
          READ_ONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.ci/releasenotes-gen.sh
