#############################################################################
# GitHub Action to Upload '-all' Jar.
#
#############################################################################
name: "R: Upload '-all' Jar"
run-name: "R: Upload '-all' Jar ${{ inputs.version }}"
on:
  push:
    branches: [ checkstyle ]



















jobs:
  upload-all-jar:
    name: Upload '-all' jar ${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Setup local maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run GitHub Update Script
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          ./.ci/release-upload-all-jar.sh ${{ inputs.version }}
