#############################################################################
# GitHub Action to Publish Release Notes to GitHub Release Page.
#
#############################################################################
name: "R: Update GitHub Page"
run-name: "R: Update GitHub Page ${{ inputs.version }}"
on:
  push:
    branches: [ checkstyle ]
















jobs:
  update-github-page:
    name: Update GitHub Page ${{ inputs.version }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Setup local maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run Shell Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          ./.ci/release-update-github-page.sh ${{ inputs.version }}
