name: Release Contributors Workflow

on:
  push:
    branches: [ debezium ]









jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      - name: Run script
        run: |
          ./github-support/list-contributors.sh ${{ github.event.inputs.tag1 }} ${{ github.event.inputs.tag2 }}
