#############################################################################
# GitHub action to set latest milestone on issue of merged PR.
#
#############################################################################
name: 'Milestone issue closed by PR'

on:
  push:
    branches: [ checkstyle ]












jobs:
  set-milestone:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Set milestone on issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.ci/set-milestone-on-referenced-issue.sh '${{ toJSON(github.event.commits) }}'
