name: Build Website

on:
  push:
    branches: [ debezium ]







jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PUBLISH_GH_TOKEN}}
          repository: debezium/debezium.github.io
          event-type: documentation-update-event
